config/routes.rb
Rails.application.routes.draw do

  resources :sessions, only: [:new, :create]
  delete 'logout', to: 'sessions#destroy', as: 'session'

  # resources
  resources :customer, only: [:index, :show, :new, :create]
  get "/:page" => "pages#show"
  resources :credits

  # static pages
  get "/:page" => "pages#show"

  # root page
  root 'pages#show'


end

app/models/credit.rb
class Credit < ActiveRecord::Base
  belongs_to :customer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :guid, :authorize

  #
  # redirects user to root if not logged in
  #

  def authorize
    unless is_authorized?
      redirect_to root_url
    end
  end

  #
  # tells view if someone is logged in
  #

  helper_method :is_authorized?
  def is_authorized?
    if session[:auth_code].blank?
      return false
    else
      return true
    end
  end

  def guid
    # only if it doesn't exist already?
    if session[:guid].blank?
      session[:guid] = SecureRandom.urlsafe_base64
    end
    return session[:guid]
  end

  def append_info_to_payload(payload)
    super
    payload[:host] = request.host
    payload[:guid] = guid
    payload[:env] = Rails.env.to_s
    payload[:level] = Rails.logger.level

  end
end

app/controllers/credits_controller.rb
require "#{Rails.root}/lib/square_api"

class CreditsController < ApplicationController
  before_action :set_credit, only: [:show, :edit, :update, :destroy]

  # GET /credits
  # GET /credits.json
  def index
    @credits = Credit.all
  end

  # GET /credits/1
  # GET /credits/1.json
  def show
  end

  # GET /credits/new
  def new
    @credit = Credit.new(customer_id: params[:customer_id])

    # customer name
    customer = SquareApi.new.get_squareup_customer(params[:customer_id])
    @customer_name = "#{customer['given_name']} #{customer['family_name']}"
  end

  # GET /credits/1/edit
  def edit
  end

  # POST /credits
  # POST /credits.json
  def create
    @credit = Credit.new(credit_params)

    # TODO check if new credit sends customer into negative

    respond_to do |format|
      if @credit.save
        format.html { redirect_to customer_url(id: @credit.customer_id), notice: 'Credit was successfully created.' }
        format.json { render :show, status: :created, location: @credit }
      else
        format.html { render :new }
        format.json { render json: @credit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /credits/1
  # PATCH/PUT /credits/1.json
  def update
    respond_to do |format|
      if @credit.update(credit_params)
        format.html { redirect_to customer_url(id: @credit.customer_id), notice: 'Credit was successfully updated.' }
        format.json { render :show, status: :ok, location: @credit }
      else
        format.html { render :edit }
        format.json { render json: @credit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /credits/1
  # DELETE /credits/1.json
  def destroy
    customer_id = @credit.customer_id
    @credit.destroy
    respond_to do |format|
      format.html { redirect_to customer_url(id: customer_id), notice: 'Credit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_credit
      @credit = Credit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def credit_params
      params.require(:credit).permit(:amount, :customer_id)
    end
end

app/controllers/customer_controller.rb
require 'rest-client'
require "#{Rails.root}/lib/square_api"

class CustomerController < ApplicationController

  def index
    # get customers and put into a variable
    @customers = SquareApi.new.get_squareup_customers()

    # filter customers names
    unless params[:search].blank?
      @customers = @customers.select {|c| c['given_name'].downcase.include? params[:search].downcase.strip }
    end
    # variable.count puts into variable
    @results_count = @customers.count

  end

  def show

    # squareup customer
    @customer = SquareApi.new.get_squareup_customer(params['id'])

    # credit history
    @credits = Credit.where(customer_id: params['id']).order('created_at desc')

    # remaining credits
    @count_credits = @credits.sum(:amount)
  end

  def new

  end

  def create

    customer_hash = {
      given_name: params[:first],
      family_name: params[:last]
    }

    response = SquareApi.new.create_squareup_customer(customer_hash)
    redirect_to customer_index_path

  end

  private


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  skip_before_filter :authorize

  def show
    if params[:page].blank?
      render template: "pages/home"
    else
      render template: "pages/#{params[:page]}"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_filter :authorize, except: [:destroy]

  def new
  end

  def create

    # test for password
    if params[:password]=='magic'

      # set session and let them in
      session[:auth_code] = true
      redirect_to customer_index_path(notice: 'Successfully Logged In.')

    else

      # fail
      redirect_to new_session_url(notice: 'Login Failed')
    end
  end

  def destroy
    session[:auth_code] = nil
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/credits_helper.rb
module CreditsHelper
end

app/helpers/customer_helper.rb
module CustomerHelper
  def count_credits(customer_id)
    Credit.where(customer_id: customer_id).sum(:amount)
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/credits/_form.html.erb
<%= form_for(@credit) do |f| %>
  <% if @credit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@credit.errors.count, "error") %> prohibited this credit from being saved:</h2>

      <ul>
      <% @credit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount, type: 'number' %>
  </div>

  <div class="field">
    <%= f.label :customer_id %><br>
    <%= @customer_name %>
    <%= f.hidden_field :customer_id %>
  </div>

  <div class="actions module">
    <%= f.submit %>
  </div>
<% end %>

app/views/credits/_table.erb
<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th>Create Date</th>
      <th colspan="2" width="180"></th>
    </tr>
  </thead>

  <tbody>
    <% credits.each do |credit| %>
      <tr>
        <td><%= credit.amount %></td>
        <td><%= credit.created_at.strftime("%m/%d/%Y at %I:%M%p") %></td>
        <td><%= link_to 'Edit', edit_credit_path(credit) %></td>
        <td><%= link_to 'Destroy', credit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/credits/edit.html.erb
<div class="module-container">
  <div class="container module">

  <h1>Editing Credit</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @credit %> |
  <%= link_to 'Back', customer_index_path %>

  </div>
</div>

app/views/credits/index.html.erb
<div class="module-container">
  <div class="container module">

    <p id="notice"><%= notice %></p>

    <h1>Listing Credits</h1>

    <%= render partial: 'table', locals: { credits: @credits } %>

    <br>

    <%= link_to 'New Credit', new_credit_path %>

  </div>
</div>

app/views/credits/new.html.erb
<div class="container-wrapper">
  <div class="container module">
    <h1>New Credit</h1>

    <%= render 'form' %>

    <%= link_to 'Back', customer_index_path %>
  </div>
</div>

app/views/credits/show.html.erb
<div class="module-container">
  <div class="container module">

    <p id="notice"><%= notice %></p>

    <p>
      <strong>Amount:</strong>
      <%= @credit.amount %>
    </p>

    <p>
      <strong>Customer:</strong>
      <%= @credit.customer_id %>
    </p>

    <%= link_to 'Edit', edit_credit_path(@credit) %> |
    <%= link_to 'Back', customer_index_path %>

  </div>
</div>

app/views/customer/index.html.erb
<div class="container">

  <p id="notice"><%= notice %></p>

  <h1>Customers</h1>

  <%= form_tag customer_index_path, :method => 'get' do %>
    <p>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search", :name => nil %>
      <%= link_to "Clear", customer_index_path, class: 'button' %>
      <%= link_to "Add New", new_customer_path %>
    </p>
  <% end %>

  <div class="module">
    <p>We found <%= @results_count %> squareup customers</p>
    <table class="custumer-table">
      <thead>
        <tr>
          <th>Customer Name</th>
          <th>Customer's Phone</th>
          <th>Credits</th>
          <th>Adjust</th>
        </tr>
      </thead>
      <tbody>
        <% @customers.each do |c| %>
        <tr>
          <td><%= link_to "#{c['given_name']} #{c['family_name']}", customer_path(c['id']) %></td>
          <td><%= c['phone_number'] %></td>
          <td><%= count_credits c['id'] %></td>
          <td><%= link_to 'adjust', new_credit_path(customer_id: c['id'])%></td>
        </tr>
        <% end %>
      </tbody>
    </table>

  </div>
</div>

app/views/customer/new.html.erb
<div class="container-wrapper">
  <div class="container module">

    <h1>New Customer</h1>
    <%= form_tag '/customer', :method => :post  do %>
      <fieldset>
        <legend>First</legend>
        <div>
          <%= text_field_tag :first %>
        </div>

        <legend>Last</legend>
        <div>
          <%= text_field_tag :last %>
        </div>
        <div>
          <%= submit_tag "Create" %>
        </div>
    </fieldset>
    <% end %>
  </div>
</div>

app/views/customer/show.html.erb
<div class="container-wrapper">
  <div class="container">

    <h1><%= @customer['given_name'] %> <%= @customer['family_name'] %></h1>
    <p>
      <h2><%= number_to_currency @count_credits %></h2>
    </p>

    <%= link_to "Done", customer_index_path, class: 'button' %>
    <%= link_to 'Add Credit', new_credit_path(customer_id: @customer['id']), class: 'btn'%>

    <div class="module">
      <h2>Credit Transaction History</h2>

      <%= render partial: 'credits/table', locals: { credits: @credits } %>
    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Coffee Credits</title>

  <!-- Always force latest IE rendering engine or request Chrome Frame -->
  <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
  <meta name="viewport" content="width=device-width">

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller_name %> <%= action_name %>">

  <header class="site-header">
    <nav class="site-nav container" role="navigation">

      <%= link_to '/', class: 'navbar-brand' do %>
      MOUNTAIN HIGH
      <% end %>
      <ul class="nav-links">
        <li><%= link_to 'Home', '/home' %>
          <ul></ul>
        </li>
        <li><%= link_to 'Menu', '/menu' %>
          <ul></ul>
        </li>
        <% if is_authorized? %>
        <li>
          <i class="fa fa-angle-double-right"></i>

          <a href="#">Admin</a>
          <ul>
            <li>
              <%= link_to 'Customers', customer_index_path %>
              </li>
            <li><%= link_to 'Logout', session_path, :method => :delete %></li>
          </ul>
        </li>
        <% end %>
      </ul>
    </div>
    <div class="mobile-menu"><i class="fa fa-navicon"></i></div>
  </nav>
</header>



<main class="site-main">
  <%= yield %>
</main>


<footer class="site-footer">
  <div class="container">
    <div class="footer-icon">
      <p>Follow us</p>
      <a href="https://www.facebook.com/MountainHighCoffee/" target="blank">
        <i class="fa fa-facebook-square fa-3x" aria-hidden="true" ></i>
      </a>
      <a href="https://twitter.com/MountainHiCafe" target="blank">
        <i class="fa fa-twitter-square fa-3x" aria-hidden="true"></i>
      </a>
      <a href="https://www.youtube.com/user/10revver01?feature=mhee" target="blank">
      <i class="fa fa-youtube-square fa-3x" aria-hidden="true"></i>
      </a>
    </div>
    <p>
      18983 Hartmann Rd<br />
      Hidden Valley Lake, CA 95467<br />
      <a href="tel:7079878086">707-987-8086</a><br />
      <a href="mailto:mountain.high.coffee@gmail.com">mountain.high.coffee@gmail.com</a><br />
      <a target="_blank" href="http://www.mountainhighcafe.com/images/stories/MountainHighApplication.pdf" title="Job Application">Job Application</a><br />
      <%= link_to 'login', new_session_path %>
    </p>
  </div>
</footer>

<!-- bottom  -->
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= yield :js %>
<% if Rails.env == "Production" %><!-- ex. google analytics --><% end %>
<!-- /bottom  -->
</body>
</html>

app/views/pages/home.html.erb
<!--
<div class="hero-unit">
</div>

<div class="hero-unit-mobile">
</div>
-->

<div id="hero-theta">
  <div id="info" class="container">
    <div class="tagline">Excellent smoothies and tasty breakfast burritos. Nice ambience and friendly.</div>
  </div>
</div>

<div class="container-wrapper">
  <div class="container module">

    <div class="basic-panel basic-panel-coffee">
      <section class="vert">
        <%= image_tag "coffecup.png" %>
      </section>

      <section class="vert">
        <h2>Full Flavored Coffee</h2>
        <p>
          The Taylor Maid Farms roast is full flavored without the linger of bitter. We work to find the sweet spot of the coffee, capturing the aroma, body and acidity that is characteristic of the farm and the bean, not the roast. What you will taste in our coffee is what we feel best represents the care and attention paid to in on the farm.
        </p>
      </section>
    </div>

  </div>
</div><!-- end of container-container -->



<div class="container-wrapper">
  <div class="container module">

    <div class="basic-panel basic-plus-panel basic-panel-location">

      <h2>Our Store Locations</h2>
      <section>
        <h3>Hidden Valley Lake</h3>
        <p>
          18983 Hartmann Rd<br>
          Hidden Valley Lake, CA 95467<br>
          <a href="tel:7079878086">707-987-8086</a><br>
          M-F 5:30am - 5pm<br>
          S-S 6:30am - 5pm<br>
        </p>
      </section>

      <section>
        <h3>Cobb Mountain</h3>
        <p>
          The Meadows Springs Shopping Center<br>
          16295 Hwy 175<br>
          Cobb, CA 95426<br>
          <a href="tel:7079280461">707-928-0461</a><br>
          M-F 5:30am - 6pm<br>
          S-S 6:30am - 5pm<br>
        </p>
      </section>

    </div>
  </div>
</div><!-- end of container-container -->


<div class="container-wrapper">
  <div class="container module">
    <div class="row_block">
      <%= image_tag("space-work.jpg") %>
      <div class="block_content">
        <h3>Coffee & Books</h3>
        <p>
          Let's get lost in a world of books, coffee, and rainy days.
        </p>
      </div>
    </div>

    <div class="row_block">
      <%= image_tag("table-space.jpg") %>
      <div class="block_content">
        <h3>Experience</h3>
        <p>
          Mountain High offers a place to drink, work, eat, unwind, and drink again.
        </p>
      </div>
    </div>

    <div class="row_block">
      <%= image_tag("coffee-place.jpg") %>
      <div class="block_content">
        <h3>Community</h3>
        <p>
          We believe coffee is more than a product – it’s a bridge to community. We hope to bridge gaps in our community as a space that fosters conversations that matter over a product that tastes and does good.
        </p>
      </div>
    </div>
  </div>
</div>
<!-- end of three columns -->

app/views/pages/menu.html.erb
<div class="container-wrapper">
  <div class="container module">

	<h1>Which Location?</h1>
	<section>
	<h3>Hidden Valley Lake (<%= link_to 'order now', 'https://squareup.com/store/HiddenValleyLake' %>)</h3>
	<p>
	  18983 Hartmann Rd<br>
	  Hidden Valley Lake, CA 95467<br>
	  <a href="tel:7079878086">707-987-8086</a><br>
	  M-F 5:30am - 5pm<br>
	  S-S 6:30am - 5pm<br>
	</p>
	</section>

	<section>
	<h3>Cobb Mountain (<%= link_to 'order now', 'https://squareup.com/store/CobbMountain' %>)</h3>
	<p>
	  The Meadows Springs Shopping Center<br>
	  16295 Hwy 175<br>
	  Cobb, CA 95426<br>
	  <a href="tel:7079280461">707-928-0461</a><br>
	  M-F 5:30am - 6pm<br>
	  S-S 6:30am - 5pm<br>
	</p>
	</section>
	</div>
</div>